### ISSUE TITLE
gemelli and qiime2 amplicon-2024.5

### ISSUE THREAD

**Issue by ARW-UBT** [biocore/gemelli#104]
Hello, 
I have used gemelli in qiime2-amplicon-2024.2; After installation of q2-amplicon-2024.5 and installing gemelli there, I got the following downgrade messages. 
I am not sure if gemelli is compatible with q2 releases 2024.5 (and possibly the following releases). I am afraid that downgrading some packages could introduce other issues with qiime2.
Is there a newer gemelli release available? 
Best, 

Installing collected packages: nose, scipy, cython, scikit-bio, tax2tree, gemelli
  Attempting uninstall: scipy
    Found existing installation: scipy 1.13.0
    Uninstalling scipy-1.13.0:
      Successfully uninstalled scipy-1.13.0
  Attempting uninstall: scikit-bio
    Found existing installation: scikit-bio 0.6.0
    Uninstalling scikit-bio-0.6.0:
      Successfully uninstalled scikit-bio-0.6.0
Successfully installed cython-3.0.11 gemelli-0.0.12 nose-1.3.7 scikit-bio-0.5.9 scipy-1.10.1 tax2tree-1.1

**Comment by ARW-UBT** [comment]
Hi, 
I experienced a similar issue with empress: 
see: https://github.com/biocore/empress/issues/566

Marcus Fedarko was able to track this issue down to the iow package, and could solve this by upgrading iow. 
I tried the same with gemelli, and it solved also this issue here. 

Since I already had a post on q2 Forum, I will add a link there to these posts here. 

Best,

**Comment by cameronmartino** [comment]
Thanks for reporting, posting on the forum, and for using RPCA! Feel free to re-open this issue if it persists.
