### ISSUE TITLE
Adding min-feature-frequency to CTF

### ISSUE THREAD

**Issue by mestaki** [biocore/gemelli#56]
A convenient thing, I noticed that with auto-rpca one can filter based on  `min-feature-frequency` which is very useful, but this isn't available for `ctf`. Would be handy if all filtering options were available for all gemelli commands. I'm on version 0.0.7.

**Comment by cameronmartino** [comment]
@mestaki [mestaki](https://github.com/mestaki) this is now available in PR #53. Thanks!!
