### ISSUE TITLE
possible numpy-related issue

### ISSUE THREAD

**Issue by gregcaporaso** [biocore/gemelli#71]
A numpy-related failure was brought up in the context of DEICODE's `rpca` action on the QIIME 2 Forum [here](https://forum.qiime2.org/t/deicode-throwing-numpy-has-no-attribute-int-error/277700). @cameronmartino thought it might also impact gemelli, so I'm posting this here. See the forum post for the command and traceback.

**Comment by cherman2** [comment]
Seems like a user did observe this issue in q2-gemelli. (Same link as Greg used above) Here is the code they reported: 
`qiime gemelli rpca
--i-table DADA2_denoising_output/table_filtered_v2.qza
--p-min-feature-count 10
--p-min-sample-count 47500
--o-biplot core_metrics_47500/Aitchison_ordination.qza
--o-distance-matrix core_metrics_47500/Aitchison_distance.qza
--verbose
&> core_metrics_47500_Aitchison_samples.log`

Here is the error: 

> Plugin error from gemelli:
> 
> module 'numpy' has no attribute 'int'.
> np.int was a deprecated alias for the builtin int. To avoid this error in existing code, use int by itself. Doing this will not modify any behavior and is safe. When replacing np.int, you may wish to use e.g. np.int64 or np.int32 to specify the precision. If you wish to review your current use, check the release note link for additional information.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
> [NumPy 1.20.0 Release Notes — NumPy v2.0.dev0 Manual](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations)

**Comment by cameronmartino** [comment]
Hi @gregcaporaso & @cherman2, thanks for posting this, will work on patching it in the next version. Thanks!!

**Comment by cameronmartino** [comment]
Hi @gregcaporaso and @cherman2,

This is now fixed in the new release of Gemelli merged today. I will update the original thread on the forums too. Thanks!!

Cameron

**Comment by cameronmartino** [comment]
@gregcaporaso or @cherman2 

Actually, looks like the forum question was closed [here](https://forum.qiime2.org/t/deicode-throwing-numpy-has-no-attribute-int-error/27770/11) and I can't re-open it. If you could open or update the original thread, that would be great. Thanks!!
