### ISSUE TITLE
How to access the phylogenetic_rpca object

### ISSUE THREAD

**Issue by harper357** [biocore/gemelli#72]
In the 2022 paper, you show (in Fig1) the overview of the algorithm for phylo-RPCA, which generates a weighted, robust centered log-ratio table before robust aitchison PCA. Is there a way to access that table in gemelli?

**Comment by cameronmartino** [comment]
Hi @harper357,

Yes! There is a QIIME2 CLI for just that table if you would like it:

```
qiime gemelli phylogenetic-rclr-transformation --help
```

or standalone CLI

```
gemelli phylogenetic-rclr --help
```

There is also a Python API function. 

```
from gemelli.preprocessing import phylogenetic_rclr_transformation
```

This requires the table and phylogeny input and will return the table and a tip to feature the matched phylogeny.

**Comment by harper357** [comment]
Oh of course! I can't believe I didn't think to just import the function directly. Thanks!
