### ISSUE TITLE
Baseline correction in tensor factorisation. 

### ISSUE THREAD

**Issue by SilasK** [biocore/gemelli#76]
Hello, I have a dataset with timepoints and would like to apply Tensor factorisation. 

I would like to aubstract the baseline in clr space in order to normalize the inter individual differences. 

How would I do this with gemelli?

**Comment by cameronmartino** [comment]
Hi @SilasK,

Thanks for the question and using the tools! I wouldn't baseline subtract but rather run CTF normally. Then if your study design is such that you want to see the difference between groups by time from baseline, I would suggest something like the `first-distances` command in  Q2-longitudinal (see [here](https://docs.qiime2.org/2023.9/tutorials/longitudinal/#first-differencing-to-track-rate-of-change)). You could also choose log-ratios from the CTF output and then use a rate of change like the `first-differences` command in combination with PERMANOVA or a LME model. 

Hope this helps!

Cameron
