### ISSUE TITLE
Installing gemelli using the reticulate package in R

### ISSUE THREAD

**Issue by OmerKamer** [biocore/gemelli#81]
Hi, 

Is it possible to install this package using the reticulate package in R?
I installed the dependency Cython `py_install("Cython")`, and when I tried to `py_install("gemelli")` I get the following error:

`Using virtual environment "C:/Users/USER/Documents/.virtualenvs/r-reticulate" ...
+ "C:/Users/USER/Documents/.virtualenvs/r-reticulate/Scripts/python.exe" -m pip install --upgrade --no-user use-pep517
ERROR: Could not find a version that satisfies the requirement use-pep517 (from versions: none)
ERROR: No matching distribution found for use-pep517`

Thanks

**Comment by cameronmartino** [comment]
Hi @OmerKamer, 

I have never used the reticulate package but found a similar problem [here](https://github.com/vtraag/leidenalg/issues/49). Could you try doing the normal pip installation of Gemelli and then specify the Python version at the beginning of the R session (see [here](https://rstudio.github.io/reticulate/reference/use_python.html))? Your R script should look something like this (based on [this](https://github.com/vtraag/leidenalg/issues/49#issuecomment-986241054)):

First, module load anaconda3
Then create your virtual environment: your_env
After activating the environment: source activate your_env: pip install gemelli

```R
use_condaenv(condaenv = "your_env", required = TRUE)
py_run_string('import gemelli')
```

**Comment by cameronmartino** [comment]
Yeah, it seems like an environment version compatibility issue. Glad it worked within the QIIME2 env! Closing this issue. Feel free to open it again if the issue persists. 

Thanks for reporting it!
