### ISSUE TITLE
pip install missing qc_assets folder

### ISSUE THREAD

**Issue by colinbrislawn** [biocore/gemelli#87]
I was surprised to discover that `pip install gemelli` silently failed to install some files. I've never seen this before...

This folder was missing:
https://github.com/biocore/gemelli/tree/master/gemelli/q2/qc_assests
Along with this file:
https://github.com/biocore/gemelli/blob/master/gemelli/q2/qc_assests/index.html

Manually making that folder and downloading that from the repo file fixed the error.

**Comment by cameronmartino** [comment]
Hi @colinbrislawn,

This is now fixed in the latest version (v. 0.0.11) let me know if you run into any further issues. Thank you for reporting and using Gemelli!!

Cheers,

Cameron
