### ISSUE TITLE
Phylogenetic-RPCA-moving-pictures - explanation needed

### ISSUE THREAD

**Issue by ARW-UBT** [biocore/gemelli#89]
Hi, 
I used your Phylogenetic-RPCA-moving-pictures tutorial to get used to the phylogenetic-rpca. From my previous experiences using rpca via deicode - and now via gemelli - I was assuming that the direction of the taxon arrows would indicate the taxa or taxonomic groups that mostly explain the position of samples in that direction. 
In your tutorial, you wrote that by clicking on some arrows "(...) Streptococcus (g) associated with the skin/tongue body site samples.". In your example, the 'Streptococcus arrows' are the light green arrows directing to the **lower left corner** of your picture. However, in this example, the skin/tongue site samples are on the **right and top side** of the picture, almost opposite to the direction of the arrows. 

I compared this phylogenetic rpca results to the rpca in deicode at https://library.qiime2.org/plugins/deicode/19/; there is also a biplot shown (as far as I can tell using the same experiment), and there the green arrow (for Streptococcus (genus)) is directing to the middle of the skin/tongue site samples. But this is the opposite direction compared to this tutorial here. 

The meaning of the enlarged sample points after clicking on one of the arrows is, that these are the samples mostly associated with the taxa of the selected arrow, as shown in the deicode example - but I got confused by the direction of the arrows here. 

Thanks for the great tools!
Best regards

**Comment by cameronmartino** [comment]
Hi @ARW-UBT,

The arrows look more similar in 3D (along PC3) but have different features. The Streptococcus (g) arrows in RPCA are individual ASVs features in the table while the arrows in phylo-rpca are internal nodes of the phylogeny whose aggregate features/ASVs lowest common ancestors are "Streptococcus (g)", which is the sum of all the ASVs in that internal node. At the end of the day, it is essential to validate any of these features by looking at log-ratios of ASVs or aggregate sums of ASVs in the real data. The goal of Qurro is to make that easier. 

I hope this helps clear it up.

Best,

Cameron
